version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: xreply-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
      - ./data/mongodb_logs:/var/log/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - xreply-network
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        SWAGGER_HOST: localhost:3002
        MONGODB_URI: mongodb://mongodb:27017
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - ENV=dev
    depends_on:
      - mongodb
    networks:
      - xreply-network
    restart: unless-stopped

networks:
  xreply-network:
    driver: bridge